FROM node:16.19.1-alpine3.17

# Create app directory
WORKDIR /usr/src/docker-react-sample

COPY . .
#RUN npm install

#Your app binds to port 3000 so you’ll use the EXPOSE instruction to have it mapped by the docker daemon:
EXPOSE 3000

CMD ["tail", "/dev/null"]

#CMD ["npm", "start"]
